GET http://localhost:3000/api/users

### 

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "batch" : [
        {
"fullname": "Junrey Tejas",
"username": "junrey",
"email": "junreytejas@gmail.com",
"password": "sadfkj3j223923sldj"
},
{
"fullname": "Junrey Tejas",
"username": "junrey",
"email": "junreytejas@gmail.com",
"password": "sadfkj3j223923sldj"
}
    ]
}
    



###

DELETE http://localhost:3000/api/users/5fd6f73cbcf89c1f026119a1

###
PATCH http://localhost:3000/api/users/5fd6f73cbcf89c1f026119a1
Content-Type: application/json

{
    "password" : "new password"
}